name: Release Image App

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag name'
        required: true

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: demo-app

jobs:
  build-and-push-to-Google-Cloud-Repository:
    name: Setup, Build and Publish
    runs-on: az-sea-docker-svr-714
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - run: |-
        gcloud --quiet auth configure-docker

    - name: Build and Push App One
      run: |-
        if [[ "${{ github.event_name }}" == "release" ]]; then
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME-one:${{ github.event.release.tag_name }}" -f Dockerfile .
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME-one:${{ github.event.release.tag_name }}"
        else
          DATE_TAG=$(date +%Y%m%d%H%M%S)
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME-one:${{ github.event.inputs.release_tag }}-$DATE_TAG" -f Dockerfile .
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME-one:${{ github.event.inputs.release_tag }}-$DATE_TAG"
        fi
      working-directory: app-one

    - name: Build and Push App Two
      run: |-
        if [[ "${{ github.event_name }}" == "release" ]]; then
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME-two:${{ github.event.release.tag_name }}" -f Dockerfile .
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME-two:${{ github.event.release.tag_name }}"
        else
          DATE_TAG=$(date +%Y%m%d%H%M%S)
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE_NAME-two:${{ github.event.inputs.release_tag }}-$DATE_TAG" -f Dockerfile .
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME-two:${{ github.event.inputs.release_tag }}-$DATE_TAG"
        fi
      working-directory: app-two